### ISSUE TITLE
上手く変換できないWikipediaの記事を発見しました

### ISSUE THREAD

**Issue by YSRKEN** [miyaoka/japari-pedia#3]
> 『ラドン＝ニコディムの定理 - Wikipedia』
https://t.co/ABWHZJMx8L

この記事を読もうとしたところ、複数箇所の表示乱れを確認しました。
ただし、変換結果に乱数性が含まれているため、リロードするたびに表示は変わります。
- `＼へーきへーき！／`が`<span class="kemo-say">`で修飾されていない。HTMLソースを確認すると、当該箇所の近くに`<span>`があるためにごっちゃになってしまっている
![image](https://cloud.githubusercontent.com/assets/3734392/23127157/4c42ce3c-f7bd-11e6-8352-a22258e1b2cc.png)
- `">`といった謎のフレーズが見えてしまっている。理由は上記と同様と推測される
![image](https://cloud.githubusercontent.com/assets/3734392/23127295/d46275c4-f7bd-11e6-8324-4120c3589a73.png)

**Comment by miyaoka** [comment]
ありがとうございます
置換処理がタグの中の句点拾っちゃっておかしくなっちゃってますね。
その辺の処理がちょっと雑なので直します。

**Comment by miyaoka** [comment]
Fixed: https://github.com/miyaoka/japari-pedia/commit/f9c8ea88a82de32f82cf0d414f3dd82524e3bc3f#diff-9dd1aaee8def4a8fa536a328f3611b79R73
